Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (1, 'Post 1', 1, 'Post description 1', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (2, 'Post 2', 2, 'Post description 2', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (3, 'Post 3', 2, 'Post description 3', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (4, 'Post 4', 3, 'Post description 4', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (5, 'Post 5', 4, 'Post description 5', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into Post (id, title, category, description, created_date, created_by, modified_date,version) values (6, 'Post 6', 4, 'Post description 6', '2022-09-01', 'TestUser', '2022-09-21',1);
Insert into post_content values (1, 'Body 1');
Insert into post_content values (2, 'Body 2');
Insert into post_content values (3, 'Body 3');
Insert into post_content values (4, 'Body 4');
Insert into post_content values (5, 'Body 5');
Insert into post_content values (6, 'Body 6');