FROM node:16-alpine as front
WORKDIR /app
COPY src/main/reactapp/package.json /app
RUN npm install
COPY src/main/reactapp/public  /app/public
COPY src/main/reactapp/src  /app/src
RUN npm run build

FROM maven as backend
WORKDIR /back
COPY 'src/main/java'  /back/src/main/java
COPY 'src/main/resources'  /back/src/main/resources
COPY 'pom.xml'  /back
RUN mvn clean install
COPY --from=0 /app/build /back/BOOT-INF/classes/public
RUN jar uf target/forum-1.0-SNAPSHOT.jar BOOT-INF/classes/public
ENTRYPOINT ["java", "-jar", "target/forum-1.0-SNAPSHOT.jar","-Dspring.profiles.active=docker"]