FROM node:16-alpine as front
WORKDIR /front
COPY src/main/reactapp/package.json /front
RUN npm install
COPY src/main/reactapp/public  /front/public
COPY src/main/reactapp/src  /front/src
RUN npm run build

FROM maven as backend
WORKDIR /back
COPY 'pom.xml'  /back
#resolve dependencies
RUN mvn clean package -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r target/
COPY 'src/main/java'  /back/src/main/java
COPY 'src/main/resources'  /back/src/main/resources
#build the app
RUN mvn clean package

#optimizing the image
FROM openjdk:17-ea-jdk
WORKDIR /app
COPY --from=front /front/build /app/BOOT-INF/classes/public
COPY --from=backend /back/target /app/target
RUN jar uf target/forum-1.0-SNAPSHOT.jar BOOT-INF/classes/public
ENTRYPOINT ["java", "-jar", "target/forum-1.0-SNAPSHOT.jar"]