apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
  labels:
    app: postgresql
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/docker/postgres/forum/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim
  labels:
    app: postgresql
    tier: database
spec:
  volumeName: postgresql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi