apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
        - name: forum-app
          image: 'forum:v1.0'
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: postgresql