spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    open-in-view: false

  datasource:
#    url: jdbc:postgresql://localhost:5432/forum
#    url: jdbc:postgresql://host.docker.internal:6543/forum
#    url: jdbc:postgresql://postgres-db:5432/forum
    url: jdbc:postgresql://${POSTGRES_URL}:5432/forum
    username: postgres
    password: superuser

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 5672560539472483
            clientSecret:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: stlab.kar@gmail.com
    password: qazxsW123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

jwt:
  secret_key: forum

password:
  restore:
    expire:
      days: 12

pagination:
  page_size:
    min: 5
    max: 20
    default: 10

logging:
  level:
    org:
      springframework:
        security: TRACE