const MAX_EMAIL_LENGTH = 20;
const MAX_LOGIN_LENGTH = 20;
const MAX_PASSWORD_LENGTH = 20;
const MAX_TITLE_LENGTH = 50;
const MAX_DESCRIPTION_LENGTH = 100;
const MAX_CONTENT_LENGTH = 500;

export {
    MAX_EMAIL_LENGTH, MAX_LOGIN_LENGTH, MAX_PASSWORD_LENGTH, MAX_DESCRIPTION_LENGTH, MAX_TITLE_LENGTH,
    MAX_CONTENT_LENGTH
}
